### PR TITLE
Fix tooling test

### PR DESCRIPTION
**Pull request by nightfury1204**
### What is the feature/fix?
https://github.com/convox/issues-private/issues/730

### Does it has a breaking change?
no

### Checklist
- [ ] New coverage tests
- [ ] Unit tests passing
- [ ] E2E tests passing
- [ ] E2E downgrade/update test passing
- [ ] Documentation updated
- [ ] No warnings or errors on Deepsource/Codecov

### CODE REVIEW

**Review by yuriadams — APPROVED** [review]

**Review by Twsouza — COMMENTED** [review]
Is there a reason to remove this dependency?
If I'm not mistaken, it's related to the yubikey

**Comment by nightfury1204** [comment]
> Is there a reason to remove this dependency? If I'm not mistaken, it's related to the yubikey

This is failing to install, so i tried by removing the other steps didn't give any errors. So i thought since other steps are not dependent on it, no need to keep it

**Comment by Twsouza** [comment]
@nightfury1204 can you run the release action and ask Brian to test the yubikey in the CLI? just to make sure nothing breaks.
I appreciate.

**Comment by nightfury1204** [comment]
> @nightfury1204 can you run the release action and ask Brian to test the yubikey in the CLI? just to make sure nothing breaks. I appreciate.

Hey @Twsouza sorry I am probably lost in here. I can not link this with yubikey in the CLI. 
Because this one is test(runs on every pr request), it shouldn't release anything for production, right?
So i am not sure what to release in here to test?
Also I searched the `libudev-dev` in the convox repo: https://github.com/convox/convox/search?q=libudev-dev&type=code

Screenshot from 2022-12-01 19-10-53

Didn't find any other uses for this ``libudev-dev``

**Review by Twsouza — APPROVED** [review]
I thought it was the workflow to build the binary, for tests we don't need the lib. Thanks.
🔥

**Pull request merged**
