### PR TITLE
local: priority class fix

### PR DESCRIPTION
**Pull request by beastawakens**

### CODE REVIEW

**Comment by codelitt** [comment]
Shouldn't this include documentation for using this fix plus installing on ubuntu?

**Comment by ddollar** [comment]
The `k8s` provider also attempts to add this priority to itself on startup. Probably want to remove it there:

https://github.com/convox/convox/blob/282f6f27d307e4fdc33f32174bea16197143ec1b/provider/k8s/k8s.go#L229-L244

**Comment by beastawakens** [comment]
> Should this include documentation for using this fix plus installing on ubuntu?

@codelitt @jasontclark is working on this 😊

**Comment by codelitt** [comment]
@beastawakens roger!

**Comment by beastawakens** [comment]
> The `k8s` provider also attempts to add this priority to itself on startup. Probably want to remove it there:
> 
> https://github.com/convox/convox/blob/282f6f27d307e4fdc33f32174bea16197143ec1b/provider/k8s/k8s.go#L229-L244

Nice catch, thanks @ddollar ! New commit added 😊

**Review by jasontclark — APPROVED** [review]
LGTM. 👍

**Review by ddoc — APPROVED** [review]
LGTM

**Review by kaiomagalhaes — APPROVED** [review]

**Pull request merged**
