### PR TITLE
Creation of rack using existing VPC and subnet

### PR DESCRIPTION
**Pull request by lucasmacedot**
### What is the feature/fix?

** Describe the task and what is the goal for it. **
** Describe the bug and the solution. **
** Any additional information **

### Add screenshot or video (optional)

** Any screenshot or video capture using the feature **

### Does it has a breaking change?

** Describe the changes and if it has any breaking changes in any feature **

### How to use/test it?

** Describe how to test or use the feature **

### Checklist
- [ ] New coverage tests
- [ ] Unit tests passing
- [ ] E2E tests passing
- [ ] E2E downgrade/update test passing
- [ ] Documentation updated
- [ ] No warnings or errors on Deepsource/Codecov

### CODE REVIEW

**Comment by lucasmacedot** [comment]
Related: https://github.com/convox/convox/pull/604

**Comment by nightfury1204** [comment]
@lucasmacedot thanks
each subnet is on some availability zone, we use availability zone name in the node group name, so depending on the subnets it might be inconsistent, can you update to use subnets availability zone here : https://github.com/convox/convox/blob/master/terraform/cluster/aws/main.tf#L102
you can use data source for that: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnet.html

**Comment by nightfury1204** [comment]
@lucasmacedot also documentation commit is missing

**Comment by nightfury1204** [comment]
> @lucasmacedot thanks each subnet is on some availability zone, we use availability zone name in the node group name, so depending on the subnets it might be inconsistent, can you update to use subnets availability zone here : https://github.com/convox/convox/blob/master/terraform/cluster/aws/main.tf#L102 https://github.com/convox/convox/blob/master/terraform/cluster/aws/main.tf#L137 you can use data source for that: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnet.html

Hey @lucasmacedot instead you can specify in the documentation to explicitly define the respective subnets zone in the rack param `availability_zones`

**Comment by nightfury1204** [comment]
@lucasmacedot there some error:
```

Error: Duplicate local value definition

  on .terraform/modules/system/terraform/cluster/aws/network.tf line 9, in locals:
   9:   validate_private_subnets_count = length(var.private_subnets_ids) == 0 ? true : (var.high_availability ? (length(var.private_subnets_ids) == 3 ? true : tobool("If high availability is enabled, there must be 3 private subnets on each AZ")) : true)
```

**Comment by lucasmacedot** [comment]
> > @lucasmacedot thanks each subnet is on some availability zone, we use availability zone name in the node group name, so depending on the subnets it might be inconsistent, can you update to use subnets availability zone here : https://github.com/convox/convox/blob/master/terraform/cluster/aws/main.tf#L102 https://github.com/convox/convox/blob/master/terraform/cluster/aws/main.tf#L137 you can use data source for that: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnet.html
> 
> Hey @lucasmacedot if it's problematic to implement instead you can specify in the documentation to explicitly define the respective subnets zone in the rack param `availability_zones`

Yeah, I was thinking about the creation of the `aws_eks_node_group.cluster`, if the count goes to private subnets, or public subnets, or if you even want that kind of customization

**Comment by nightfury1204** [comment]
> 
> Yeah, I was thinking about the creation of the `aws_eks_node_group.cluster`, if the count goes to private subnets, or public subnets, or if you even want that kind of customization Like, what defines the number of the node_groups

@lucasmacedot i looked into pr more deeply and tried to deploy rack with it. i found couple of issues, so it's better i spend time on it to fix/reimplement

**Comment by nightfury1204** [comment]
@lucasmacedot hey i fixed and rewrote the logic little bit. pushed in another PR: https://github.com/convox/convox/pull/682, since i don't have permission to the branch.

**Pull request closed without merging**
