### PR TITLE
Adding in whitelist option at the service level

### PR DESCRIPTION
**Pull request by beastawakens**
PR incoming for `rack` as well to maintain parity to v2.

### CODE REVIEW

**Comment by heronrs** [comment]
@beastawakens this is only for apps that define their own load balancer, right?

**Comment by beastawakens** [comment]
@heronrs no, the whitelist option on custom balancers already exists.  This change allows you to add a whitelist on the service level ingress object itself so it's easier!  You don't need a separate balancer if you just want to whitelist 😄

**Comment by beastawakens** [comment]
Is this all good to merge @heronrs ? 😄

**Comment by beastawakens** [comment]
@heronrs finally remembered to fix the tests 😆

**Comment by NilsJPWerner** [comment]
@beastawakens this is incredible! Does this require proxy_protocol to be turned on?

**Comment by beastawakens** [comment]
> @beastawakens this is incredible! Does this require proxy_protocol to be turned on?

It does, otherwise the IP coming through is just an internal one so makes it kinda pointless 😄 But once that's on, it works great!

**Pull request merged**
