### PR TITLE
Update some dependencies to avoid convox being unlisted from homebrew

### PR DESCRIPTION
**Pull request by yuriadams**
[task 608](https://github.com/convox/issues-private/issues/608)

```
k8s.io/api v0.20.15  ->  v0.21.0
k8s.io/apimachinery  v0.20.15  ->  v0.21.0
k8s.io/client-go v0.20.15  -> v0.21.0
k8s.io/code-generator v0.20.15  -> v0.21.0
k8s.io/metrics v0.20.15 -> v0.21.0
```

### CODE REVIEW

**Review by Twsouza — COMMENTED** [review]
LGTM, just run the e2e test and I will approve it :D

**Comment by yuriadams** [comment]
Cool, @Twsouza! I'm having some errors in the uninstall step of the e2e tests. I'm trying to figure out what to do. Is there any opened issue for that?

**Comment by Twsouza** [comment]
@yuriadams which error? can you send me the link to the test?

**Comment by yuriadams** [comment]
this is an example, @Twsouza: https://github.com/convox/convox/actions/runs/3114231503/jobs/5074100425

**Review by nightfury1204 — APPROVED** [review]
LGTM
can you confirm all e2e test are passing?

**Review by Twsouza — COMMENTED** [review]
LGTM

**Pull request merged**
