### PR TITLE
Fix creation of rack using existing subnets

### PR DESCRIPTION
**Pull request by lucasmacedot**
### What is the feature/fix?

** Describe the task and what is the goal for it. **
** Describe the bug and the solution. **
** Any additional information **

### Add screenshot or video (optional)

** Any screenshot or video capture using the feature **

### Does it has a breaking change?

** Describe the changes and if it has any breaking changes in any feature **

### How to use/test it?

** Describe how to test or use the feature **

### Checklist
- [ ] New coverage tests
- [ ] Unit tests passing
- [ ] E2E tests passing
- [ ] E2E downgrade/update test passing
- [ ] Documentation updated
- [ ] No warnings or errors on Deepsource/Codecov

### CODE REVIEW

**Review by Twsouza — CHANGES_REQUESTED** [review]
LGTM but you need to rebase your staging branch, there are some duplicated commits

**Comment by lucasmacedot** [comment]
@Twsouza 

> LGTM but you need to rebase your staging branch, there are some duplicated commits

Is it allright now?

**Comment by ntner** [comment]
@lucasmacedot when incorporating this into the last release candidate it was causing errors so we removed it due to time constraints.  We will attempt again at the next release cycle to see how it goes.

**Comment by Twsouza** [comment]
@lucasmacedot you need to reopen https://github.com/convox/convox/pull/563 because when we tried to merge to master.

**Comment by lucasmacedot** [comment]
Ok, will do

**Comment by lucasmacedot** [comment]
@Twsouza I saw that you already merged the #563
You still need me to reopen it?

**Comment by lucasmacedot** [comment]
Just opened a new PR to staging: https://github.com/convox/convox/pull/604

@Twsouza

**Pull request closed without merging**
