### PR TITLE
Fix: Internal router fix

### PR DESCRIPTION
**Pull request by nightfury1204**
### What is the feature/fix?

https://app.asana.com/0/1203637156732418/1204515779330565/f

Aws changes the default preserve client ip policy. for internal router perserve client ip policy has to be off.

### Does it has a breaking change?
no

### How to use/test it?

- deploy rack of this version: `nahid-internal-router`
- test the internal router

### Checklist
- [ ] New coverage tests
- [ ] Unit tests passing
- [ ] E2E tests passing
- [ ] E2E downgrade/update test passing
- [ ] Documentation updated
- [ ] No warnings or errors on Deepsource/Codecov

### CODE REVIEW

**Review by yuriadams — APPROVED** [review]

**Comment by nightfury1204** [comment]
@beastawakens user this release: https://github.com/convox/convox/releases/tag/3.12.1

**Comment by beastawakens** [comment]
@nightfury1204 testing with 3.12.1, I can see the internal LB address is now populating in the k8s ingress 🙌🏼
However, I'm still struggling to get a response from the internal service.  
With `curl` from a place inside the VPC, I am getting this:

```
* Connected to internal.testing.xxxxxxxxxxxxxxxx.convox.cloud (10.1.126.174) port 80 (#0)
> GET / HTTP/1.1
> Host: internal.testing.xxxxxxxxxxxxxxxx.convox.cloud
> User-Agent: curl/7.64.0
> Accept: */*
> Connection: keep-alive
>
* Empty reply from server
* Connection #0 to host internal.testing.xxxxxxxxxxxxxxxx.convox.cloud left intact
curl: (52) Empty reply from server
```

I'm still wondering if this is some TLS issue or incompatibility? I have `tls:  redirect: false` in the convox.yml for the service as well, as the internal LB is only exposing port 80.  Is the `nginx-internal` expecting an SSL cert?

It feels like I must just be missing something obvious that's not clear 😆 Can you provide an example of accessing perhaps?

**Comment by nightfury1204** [comment]
@beastawakens for internal router it tls will be insecure(it will use selfsigned cert). But not sure why that's not working for you. did you enabled proxy protocol?
can you share your rack params?

**Comment by beastawakens** [comment]
Hmmm, so I'm doing a curl to `http://internal.testing.xxx.convox.cloud` (service called `internal`, app called `testing` as per https://github.com/beastawakens/convox-internal-example/blob/main/convox.yml), so no https involved at all, as the internal NLB is only exposing port 80:

```
╰─ kubectl get ingress -n dev-us-testing
NAME                CLASS            HOSTS                                            ADDRESS                                                                         PORTS     AGE
external            nginx            external.testing.xxx.convox.cloud   acxxx-xxx.elb.us-west-2.amazonaws.com   80, 443   24h
internal-internal   nginx-internal   internal.testing.xxx.convox.cloud   a8xxx-xxx.elb.us-west-2.amazonaws.com   80        24h
```



Proxy protocol is enabled.
Rack params are:

```
╰─ convox rack params
high_availability   false
internal_router     true
key_pair_name       dev-us-keypair-xxx
node_capacity_type  spot
node_disk           50
node_type           t3a.large,r5.large,t3.large
proxy_protocol      true
region              us-west-2
release             3.12.1
```

**Comment by beastawakens** [comment]
@nightfury1204 If I try to curl to `https`, I receive this:

```
/usr/src/app # curl -k https://internal.testing.xxx.convox.cloud/
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to internal.testing.xxx.convox.cloud:443
```

The `-k` option should allow to ignore insecure or self-signed certs so I'm not sure what's happening there.

**Pull request merged**
