### PR TITLE
Feat-651: Add wildcard domain flag for v2 racks

### PR DESCRIPTION
**Pull request by nightfury1204**
### What is the feature/fix?
https://github.com/convox/issues-private/issues/651

Add a wildcard flag for wildcard domain for review app

Check details in below PR:
https://github.com/convox/rack/pull/3598

### Checklist
- [ ] New coverage tests
- [x] Unit tests passing
- [ ] E2E tests passing
- [ ] E2E downgrade/update test passing
- [ ] Documentation updated
- [ ] No warnings or errors on Deepsource/Codecov

### CODE REVIEW

**Review by heronrs — COMMENTED** [review]
Do we need this param even though it's only available for v2 racks?
I guess if we don't add it, it will break marshaling of the  buildCreate API call?

**Comment by nightfury1204** [comment]
> Do we need this param even though it's only available for v2 racks? I guess if we don't add it, it will break marshaling of the buildCreate API call?

It's necessary as you mentioned for the buildCreate API call

**Comment by nightfury1204** [comment]
> @nightfury1204 you will need to add the param to the [action-build](https://github.com/convox/action-build) action.

@Twsouza sorry why do we need it there?

**Comment by Twsouza** [comment]
> @Twsouza sorry why do we need it there?

oh sorry, this param will only be used by the console to create the review app?
Some users use GitHub actions for their CI process, however, they can't create review apps in this case.

**Pull request merged**
